spring :
  datasource :
    url : jdbc:mysql://localhost:3306/school?characterEncoding=utf-8&serverTimezone=GMT
    username : root
    password : 123456
    driverClassName : com.mysql.cj.jdbc.Driver
mybatis :
  config-location : classpath:/mybatis-config.xml
# JWT
jwt:
  header: Token
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "